#CALCULO DO PERIMETRO E AREA DE UM RETANGULO (PERIMETRO 2 x Largura x altura)
altura = float (input("Qual a altura do retangulo ? "))
largura = float (input("Qual a largura do retangulo ? "))
perimetro = (2 * (largura + altura))
print (f"O perimetro é =  {perimetro}")
